### PR TITLE
Suppress whereami output when starting console sessions

### LINKED ISSUE #9: Don't start the debugger when running `rails console` or `pry` command (as opposed to using binding.pry in a file)
With `pry-rails` gem installed in a rails app, when you start the `rails console`, you get a normal pry session like this:
```
⟫ rails c
Loading development environment (Rails 5.2.3)
[1] pry(main)> 
```

But as soon as you also add the `pry-moves` gem to the project, you get this as your starting point instead:

```
⟫ rails c
Loading development environment (Rails 5.2.3)

Frame: 0/30 method
From: pry-moves/lib/pry-moves/pry_ext.rb:14 Pry

     4: def start_with_pry_nav(target = TOPLEVEL_BINDING, options = {})
     5:   old_options = options.reject { |k, _| k == :pry_remote }
     6: 
     7:   if target.is_a?(Binding) && PryMoves.check_file_context(target)
     8:     # Wrap the tracer around the usual Pry.start
     9:     PryMoves::PryWrapper.new(target, options).run do
    10:       start_without_pry_nav(target, old_options)
    11:     end
    12:   else
    13:     # No need for the tracer unless we have a file context to step through
 => 14:     start_without_pry_nav(target, old_options)
    15:   end
    16: end

[1] pry(Pry)> 
```

Pry seems to still work for the most part, but it adds unwanted noise and is surprising to see a debugger context where I'm just expecting a normal REPL.

By the way, I get the same thing when I just run `bundle exec pry`, so it doesn't even seem like it's a Rails-specific problem.

It seems like the pry-moves debugger should not be enabled in the context of a rails console — until and unless some code _in a file_ explicitly calls `binding.pry`.

Ironically, the comment line for the branch that it appears to be taking even implies that it correctly detected that we're _not_ in a file context and _don't_ need the tracer:
```
    13:     # No need for the tracer unless we have a file context to step through
 => 14:     start_without_pry_nav(target, old_options)
```
Yet we still have the tracer.

An additional side effect is that if you happen to execute the `s` command from this context, it breaks...

```
[1] pry(Pry)> s
UncaughtThrowError: uncaught throw :breakout_nav
from pry-moves/lib/pry-moves/commands.rb:67:in `throw'
bundler: failed to load command: pry (/home/tyler/.gem/ruby/2.6.0/bin/pry)
NoMethodError: private method `eval' called for nil:NilClass
```

I'm not even sure how to fix this because I don't understand what's causing it to get to that code.

### PR DESCRIPTION
**Pull request by nilbus**
As suggested in https://github.com/garmoshka-mo/pry-moves/issues/9#issuecomment-513663756, this branch prevents `WhenStartedHook` from printing `whereami` output when initiating a console session.

When starting pry from a console (e.g. rails, guard, and gems generated via bundler all use Pry.start), no whereami output is printed. When starting a `binding.pry` session and when stepping through code, `whereami` output is printed at each step.

Feedback and suggested improvements are welcome!

Fixes #9

Context
-------

When starting pry, output normally looks like this:

```
$ bundle exec pry
[1] pry(main)>
```

But as soon as you also add the `pry-moves` gem to the project, you get this as your starting point instead:

```
$ bundle exec pry

Frame: 0/16 method
From: lib/pry-moves/pry_ext.rb:14 Pry

     4: def start_with_pry_nav(target = TOPLEVEL_BINDING, options = {})
     5:   old_options = options.reject { |k, _| k == :pry_remote }
     6:
     7:   if target.is_a?(Binding) && PryMoves.check_file_context(target)
     8:     # Wrap the tracer around the usual Pry.start
     9:     PryMoves::PryWrapper.new(target, options).run do
    10:       start_without_pry_nav(target, old_options)
    11:     end
    12:   else
    13:     # No need for the tracer unless we have a file context to step through
 => 14:     start_without_pry_nav(target, old_options)
    15:   end
    16: end

[1] pry(main)>
```

Included fixes
--------------

- Update outdated Gemfile.lock files
- Exclude internal pry and pry-moves frames from bindings

    With pry-moves loaded, Pry#start_with_pry_moves replaces Pry#start. With the current version of pry, Pry::CLI#start also needs to be removed. These are now removed from pry-stack_explorer's bindings.

    The initial prompt now reads

        [1] pry(main)>

    instead of

        [1] pry(Pry)>

    This matches the behavior of pry without pry-moves.

Behavior of Object#pry
----------------------

If pry is started via `pry` or `some_object.pry` (instead of `binding.pry`), pry-moves currently does not automatically print `whereami` output until the user moves up/down the stack, starts tracing, or explicity executes `whereami`. If it had been easy, I would have made this scenario act like binding.pry, but I had more trouble with it than I thought it was worth. Instead, it acts like `Pry.start`.

### CODE REVIEW

**Comment by nilbus** [comment]
This needs a tweak. Although everything seems to work fine, when this gem is loaded, the prompt changes (e.g. with guard) from
```
[1] guard(main)>
```
to
```
[1] guard(#<Guard::Jobs::PryWrapper>)>
```

It works as expected when just pry is loaded, but not from other consoles (e.g. Rails).

I'll look into this soon.

**Comment by garmoshka-mo** [comment]
@nilbus thank you for careful implementation of solution

Though it looks pretty complex. I created commit, which verifies `target` and doesn't save Stack when there is signs, that code currently runs from console.

https://github.com/garmoshka-mo/pry-moves/commit/4866270513f4888bd9439b4aa7d02880aa18bb14#diff-00e8e23b39f5e8aaaf461f5881ea751e

Published new gem version, does it works fine?

**Comment by nilbus** [comment]
It works beautifully! Thanks for coming up with something simpler and more elegant. I like your solution.

You should be good to close #9 now.

Would you mind adding and pushing a tag on the commit you released as 0.1.11? It's hard to tell what commit any of the gem versions are built on because of the lack of tags on the GitHub repo. Thanks!

**Comment by garmoshka-mo** [comment]
👍  @nilbus added tag for latest version

**Pull request closed without merging**
